### ISSUE TITLE
Download Button

### ISSUE THREAD

**Issue by rzigante** [tylerjrichards/st-filter-dataframe#1]
Hi! If i want to download the filtered DF what i need to add to the code?

Sorry im new to streamlit

**Comment by tylerjrichards** [comment]
hey @rzigante! So the function filter_dataframe actually returns the edited dataframe, so to download the filtered dataframe you need to take the result from the function, make it a csv, and then use st.download_button() to add a download section to your app. On the example app in this repo, the code would look like this.

```
my_new_dataframe = filter_dataframe(df)
st.dataframe(my_new_dataframe)
my_csv = my_new_dataframe.to_csv().encode("utf-8")

st.download_button(
    "Press to Download", my_csv, "file.csv", "text/csv", key="download-csv"
)
```
I added a screenshot too to show how it looks

![CleanShot 2022-10-13 at 09 46 21](https://user-images.githubusercontent.com/16867691/195656594-9993add2-9aab-4029-9228-8f06a32a0a30.png)

**Comment by rzigante** [comment]
Thanks!

**Comment by rzigante** [comment]
I continue getting the next error

File "temp.py", line 110, in <module>
    my_new_dataframe = filter_dataframe(df)
File "temp.py", line 38, in filter_dataframe
    modify = st.checkbox("Add filters")

I tried to use key parameter on line 38 but did not work, you used any key?

**Comment by tylerjrichards** [comment]
can you show me your whole python file or what error shows up?

**Comment by rzigante** [comment]
The code it's the same as you

In Anaconda promt i get this

Traceback (most recent call last):
  File "C:\Users\rodri\anaconda3\lib\site-packages\streamlit\scriptrunner\script_runner.py", line 557, in _run_script
    exec(code, module.__dict__)
  File "untitled0.py", line 101, in <module>
    my_new_dataframe = filter_dataframe(df)
  File "untitled0.py", line 28, in filter_dataframe
    modify = st.checkbox("Add filters")
  File "C:\Users\rodri\anaconda3\lib\site-packages\streamlit\elements\checkbox.py", line 92, in checkbox
    return self._checkbox(
  File "C:\Users\rodri\anaconda3\lib\site-packages\streamlit\elements\checkbox.py", line 133, in _checkbox
    checkbox_state = register_widget(
  File "C:\Users\rodri\anaconda3\lib\site-packages\streamlit\state\widgets.py", line 199, in register_widget
    raise DuplicateWidgetID(
streamlit.errors.DuplicateWidgetID: There are multiple identical `st.checkbox` widgets with the
same generated key.

DuplicateWidgetID: There are multiple identical st.checkbox widgets with the same generated key.

When a widget is created, it's assigned an internal key based on its structure. Multiple widgets with an identical structure will result in the same internal key, which causes this error.

To fix this error, please pass a unique key argument to st.checkbox.

Traceback:
File "untitled0.py", line 101, in <module>
    my_new_dataframe = filter_dataframe(df)
File "untitled0.py", line 28, in filter_dataframe
    modify = st.checkbox("Add filters")

Regards!

**Comment by rzigante** [comment]
It was necesary to delete st. dataframe(filter_dataframe(df)) to make sure this works, 
Thanks @tylerjrichards you are awesome!

**Comment by tylerjrichards** [comment]
oh awesome! Great :)
