### ISSUE TITLE
Import as a package

### ISSUE THREAD

**Issue by nachouve** [tylerjrichards/st-filter-dataframe#3]
Just a little wish.

I think it would be great to have *filter_dataframe* as a package available to install via pip. 

So I could have this component more clearly located in requirements.txt .

**Comment by tylerjrichards** [comment]
hey! we actually have this function inside streamlit-extras, which is a package that the streamlit data team maintains. You can see how it works here https://extras.streamlit.app/Dataframe%20explorer%20UI
